/**
 * The Kenzi Files as a hierarchical knowledge graph.
 * Each section is a graph node. Each evidence file is its own sub-graph.
 * The master document connects all sub-graphs.
 */

export interface DocumentSection {
  id: string;
  number: number;
  title: string;
  content: string;  // Current understanding — regenerated by AI when new evidence percolates
  exhibits: string[];  // exhibit IDs referenced
  evidence_ids: string[];  // cubby evidence IDs
  cross_references: Array<{ section_id: string; reason: string; strength: number }>;
  key_entities: string[];
  key_facts: string[];  // bullet points of proven facts
  gaps: string[];  // what's still missing
  last_regenerated: string;
  regeneration_log: Array<{ date: string; trigger: string; changes: string }>;
}

export interface EvidenceGraph {
  id: string;
  title: string;
  type: string;
  source: string;
  date: string;
  summary: string;  // Regenerated when graph is affected by new material
  key_findings: string[];
  entities: string[];
  connected_sections: string[];  // which document sections this evidence supports
  connected_evidence: Array<{ id: string; relationship: string }>;
  chain_of_custody: string[];
  last_regenerated: string;
}

// === THE 18 SECTIONS ===

export const DOCUMENT_SECTIONS: DocumentSection[] = [
  {
    id: 'section-1', number: 1, title: 'Fabrication of Credentials and Identity',
    content: `Kenzi constructed an entirely false professional identity to induce trust and gain access to projects and investor funds. During his initial meeting with Cere's CEO at the Battery Club in 2016, he falsified his educational background, claiming degrees from Columbia University and an MBA from Wharton. Independent investigations and the National Student Clearinghouse confirmed these claims were outright lies; his former business partner Alex Gold verified Kenzi actually attended only UNLV.

He further fabricated his business record — claiming Traction Labs was "successfully acquired in 2017" when it actually collapsed. He manufactured credibility through a paid Wikitia biography with fabricated citations to TechCrunch, Forbes, and BusinessInsider. None of these cited articles exist.

Every credential Kenzi used to gain entry into Cere Network and dozens of other projects was a misrepresentation or outright falsification serving as the foundation for his eventual theft.`,
    exhibits: ['exhibit-1'],
    evidence_ids: ['qri-report-1', 'qri-report-3', 'kenzi-files-pdf'],
    cross_references: [
      { section_id: 'section-3', reason: 'Aliases used to maintain fabricated identity across platforms', strength: 0.92 },
      { section_id: 'section-18', reason: 'Fake credentials enabled unlicensed broker-dealer activity', strength: 0.85 },
    ],
    key_entities: ['Kenzi Wang', 'Columbia University', 'Wharton', 'Wikitia', 'Alex Gold', 'Traction Labs', 'UNLV'],
    key_facts: [
      'National Student Clearinghouse: no Columbia record found',
      'Alex Gold confirmed: attended UNLV only',
      'Wikitia page created Jul 2025 by paid account "Ankush.srg"',
      '5 of 15 citations are dead links (404) — articles never existed',
      'Claims involvement with Tesla, SpaceX — no verifiable evidence',
      'Kicked out of Y Combinator for submitting under two companies',
    ],
    gaps: [],
    last_regenerated: '2026-03-23',
    regeneration_log: [
      { date: '2023-11-17', trigger: 'qri-report-3', changes: 'Added Emmie Chang testimony confirming fake Columbia/Wharton' },
      { date: '2026-02-01', trigger: 'kenzi-files-pdf', changes: 'Added Wikitia paid page analysis with fabricated citations' },
    ],
  },
  {
    id: 'section-2', number: 2, title: 'Grand Theft Conviction and Criminal History',
    content: `Kenzi is not new to crime. On November 13, 2018, he was charged with Grand Theft in San Francisco County Superior Court (Case No. 18017577, California Penal Code Section 487(a)). The charge was filed by his former employer HBUS (Huobi US) after Kenzi stole a company laptop and refused to return it. The HBUS CEO stated: "We had to file a criminal complaint to get our stolen laptop back with passwords and IP."

Kenzi worked at Huobi for three and a half months, not the "five years as Vice President and General Manager" he claims. The same year, he sued SuperBloom co-founder Emmie Chang after she caught him self-dealing — the case was dismissed after his own lawyer dropped him as a client. In 2017, a FORUM arbitration panel found Kenzi acted in "bad faith" in domain squatting.

This criminal record predates his involvement with Cere Network by years, demonstrating that Kenzi's entry into Cere was not a business venture but the continuation of a documented trajectory of falsification and theft.`,
    exhibits: ['exhibit-2'],
    evidence_ids: ['qri-report-1', 'qri-report-2'],
    cross_references: [
      { section_id: 'section-12', reason: 'Same theft pattern: steal property entrusted to him', strength: 0.80 },
    ],
    key_entities: ['Kenzi Wang', 'HBUS', 'Huobi', 'Emmie Chang', 'SuperBloom'],
    key_facts: [
      'Case No. 18017577 — Grand Theft felony charge, Nov 13, 2018',
      'HBUS CEO: "had to file criminal complaint to get laptop back"',
      'Worked at Huobi ~3.5 months, claims 5 years as VP/GM',
      'Sued Emmie Chang — dismissed after his own lawyer dropped him',
      'FORUM Case FA1709001750913 — "bad faith" domain squatting finding',
    ],
    gaps: [],
    last_regenerated: '2023-09-22',
    regeneration_log: [
      { date: '2023-09-22', trigger: 'qri-report-1', changes: 'Initial section created from QRI investigation' },
    ],
  },
  {
    id: 'section-3', number: 3, title: 'False Identities and Aliases',
    content: `Kenzi's legal name is Ken Zi Wang, confirmed through photographic copies of his passport, court records and his wedding listing. He operates under at least 8 documented aliases across multiple platforms to facilitate fraud, evade accountability, and destroy evidence.

This is not casual Web3 pseudonymity — it is the deliberate falsification of identity to execute theft. He operated as "Miles Archer" on Telegram to hijack Cere's 75,000-member community. He created "Kenzi Nakamura" on X/Twitter. Most disturbingly, he used the names of his family: his ex-girlfriend's name "Anete Vancane" on the Republic whitelist, and his mother Ye Minzhi's X account to secure additional tokens while operating from the UAE.

He controls at least six domains including the fraudulent cerenetwork.io and cerenetworkvictims.com. Each falsified identity acts as a deliberate mechanism for criminal extraction.`,
    exhibits: ['exhibit-3'],
    evidence_ids: ['kenzi-files-pdf'],
    cross_references: [
      { section_id: 'section-1', reason: 'Aliases maintain the fabricated identity', strength: 0.92 },
      { section_id: 'section-16', reason: 'Vivian Liu wallet substitution may have used alias account', strength: 0.75 },
      { section_id: 'section-17', reason: 'Multiple aliases enable syndicate operations', strength: 0.80 },
    ],
    key_entities: ['Ken Zi Wang', 'Miles Archer', 'Kenzi Nakamura', '@0xkenzi', '@GPTAutist', 'Anete Vancane', 'Ye Minzhi'],
    key_facts: [
      'Legal name confirmed: Ken Zi Wang (passport, court records)',
      '8+ documented aliases across platforms',
      'Miles Archer (@miles_archer) — Telegram community hijacking',
      'Used ex-girlfriend Anete Vancane for Republic whitelist',
      'Uses mother Ye Minzhi X account from UAE',
      '6+ domains including fraudulent cerenetwork.io',
    ],
    gaps: [],
    last_regenerated: '2026-02-01',
    regeneration_log: [],
  },
  {
    id: 'section-4', number: 4, title: 'Illegal Market Manipulation (November 2021)',
    content: `Kenzi unlawfully promoted CERE securities and, with co-conspirator Kevin Xu, executed a coordinated pump-and-dump scheme. During the "Pump" phase, Kenzi used control over financial promotion and market-making to inflate price. During the "Dump" phase, they liquidated while spreading FUD.

Facebook Messenger screenshots document Kenzi coordinating with market maker Mike Chen, Huobi listing contact Ciara, and Polygon founder Sandeep Nailwal. When the CEO flagged a calculation error in the market maker agreement, Kenzi instructed: "Just pretend you didn't see it. Sigh... They are dumb."

Kenzi subsequently pressured the CEO to pay out 800,000 USDT to LD Capital — later identified as part of his syndicate. He then deleted numerous messages from the conversation thread.`,
    exhibits: ['exhibit-4'],
    evidence_ids: ['kenzi-files-pdf'],
    cross_references: [
      { section_id: 'section-17', reason: 'LD Capital payout connects to syndicate network', strength: 0.90 },
      { section_id: 'section-15', reason: 'Pump-and-dump proceeds fed Symbolic Capital', strength: 0.70 },
      { section_id: 'section-13', reason: 'Deleted messages = evidence destruction', strength: 0.80 },
    ],
    key_entities: ['Kenzi Wang', 'Kevin Xu', 'Mike Chen', 'Ciara', 'Sandeep Nailwal', 'LD Capital'],
    key_facts: [
      '"Just pretend you didn\'t see it. Sign... They are dumb." — smoking gun quote',
      '800K USDT paid to LD Capital Dec 16, 2021 (verified on-chain)',
      'Multiple "Kenzi deleted a message" entries in Messenger logs',
      'CEO tried to halt selling: "We probably should stop selling from mm part now"',
    ],
    gaps: [],
    last_regenerated: '2026-03-23',
    regeneration_log: [],
  },
  {
    id: 'section-6', number: 6, title: 'CEO Confrontation Confirms Fraud',
    content: `When Cere's CEO confronted Kenzi about the missing $3M in stablecoins, Kenzi initially acknowledged having the funds, then refused to return them. He then fabricated a "Black Swan" story claiming the $3M was lost in a Convex Finance USDM yield pool crash.

The DHTY forensic audit (February 28, 2024) proved this was a total misrepresentation. No on-chain evidence of Convex Finance activity was found. The funds were transferred to Kenzi's personal Binance wallet without authorization. The Hyperedge LP Portal showed: Subscriptions: 0.00, Redemptions: 0.00. Cere was completely left out of the fund.`,
    exhibits: ['exhibit-6'],
    evidence_ids: ['dhty-report', 'kenzi-files-pdf'],
    cross_references: [
      { section_id: 'section-10', reason: 'Term Sheet Item 1 codifies the Black Swan lie', strength: 0.95 },
      { section_id: 'section-11', reason: 'Board investigation confirmed the theft', strength: 0.90 },
      { section_id: 'section-12', reason: 'Part of the larger $4.87M embezzlement', strength: 0.85 },
    ],
    key_entities: ['Kenzi Wang', 'Fred Jin', 'Convex Finance', 'DHTY', 'Binance', 'Hyperedge'],
    key_facts: [
      'Kenzi initially acknowledged having the $3M',
      'Then fabricated "Black Swan" Convex Finance story',
      'DHTY forensics: NO on-chain evidence of Convex activity',
      'Funds traced to personal Binance wallet',
      'Hyperedge LP Portal: Subscriptions 0.00, Redemptions 0.00',
    ],
    gaps: [],
    last_regenerated: '2024-02-28',
    regeneration_log: [
      { date: '2024-02-28', trigger: 'dhty-report', changes: 'DHTY forensics definitively disprove Black Swan narrative' },
    ],
  },
  {
    id: 'section-8', number: 8, title: 'Intimidation, Threats and Coercion',
    content: `Upon learning that Cere had engaged legal counsel, Kenzi launched an eight-month psychological harassment campaign (January-September 2022). Facebook Messenger screenshots document Kenzi threatening violence, promising to "blow everything up," threatening to delete all files and data: "I'm going to talk to all of my contacts that I brought in... I will bring all people out of the project."

He invoked Polygon's Sandeep Nailwal as leverage, weaponized the company's low market cap, and demanded $2.5 million in direct payouts. When confronted: "Very surprised you deployed lawyer on me. This is going to become messy." This was not a negotiation — it was a shakedown.`,
    exhibits: ['exhibit-8'],
    evidence_ids: ['kenzi-files-pdf'],
    cross_references: [
      { section_id: 'section-9', reason: 'Coercion led directly to the Term Sheet signing', strength: 0.95 },
      { section_id: 'section-4', reason: 'Nailwal involvement spans market manipulation and coercion', strength: 0.70 },
    ],
    key_entities: ['Kenzi Wang', 'Fred Jin', 'Sandeep Nailwal'],
    key_facts: [
      'Eight-month campaign Jan-Sep 2022',
      '"Blow everything up" — Facebook Messenger screenshots',
      'Demanded $2.5M in tokens, equity, direct payouts',
      'Invoked Sandeep Nailwal as leverage',
      '"Very surprised you deployed lawyer on me"',
    ],
    gaps: [],
    last_regenerated: '2026-03-23',
    regeneration_log: [],
  },
  {
    id: 'section-10', number: 10, title: 'Term Sheet Contains Written Confession of Theft',
    content: `The Term Sheet is Kenzi's written confession of embezzlement. He explicitly used the document to codify his falsified "Black Swan" narrative, admitting in writing (as Item 1) to taking the $3M stablecoins while insisting the company accept his excuse.

Three critical failures expose the Term Sheet as a vehicle for theft: (1) When pressed for on-chain proof of the Black Swan loss, Kenzi could not provide any evidence. (2) Kenzi never delivered on any obligation — he simply used the document to enrich himself. (3) The Term Sheet was signed under false pretense: Kenzi premeditated the scheme, stole the stablecoins outright, and violated his core duty to cease disparaging the company.

After securing his payout, he executed the full shakedown in 2023: hijacked all community channels, spread lies to advisors and investors, and intimidated Fred with draft legal claims.`,
    exhibits: ['exhibit-10'],
    evidence_ids: ['kenzi-files-pdf', 'dhty-report'],
    cross_references: [
      { section_id: 'section-6', reason: 'Black Swan narrative codified in Item 1', strength: 0.95 },
      { section_id: 'section-8', reason: 'Term Sheet was product of coercion', strength: 0.95 },
      { section_id: 'section-9', reason: 'Signed under duress — two legal theories void it', strength: 0.95 },
    ],
    key_entities: ['Kenzi Wang', 'Fred Jin'],
    key_facts: [
      'Item 1 = written admission of taking $3M stablecoins',
      'Could not provide on-chain proof of Convex Finance loss',
      'Never fulfilled any Term Sheet obligations',
      'Granted $2.49M + 18.8% equity + 861M CERE tokens',
      'After payout: executed full shakedown violating every term',
    ],
    gaps: [],
    last_regenerated: '2024-02-28',
    regeneration_log: [],
  },
  {
    id: 'section-11', number: 11, title: 'Independent Board Investigation and Forensic Audit Confirms Theft',
    content: `Refusing to succumb to the extortion, Cere's CEO reached out to Brad Bao and Francois Granada, formally appointing them as independent board members. They launched a full forensic investigation with outside counsel (Practus LLP) and independent auditors (Ascent Fund Services and DHTY).

Ascent (December 2023): proved Kenzi kept a shadow ledger and diverted $4.15 million from 79 investors. DHTY (February 2024): confirmed $4,432,400 was diverted to personal wallets and proved Kenzi stole the $3M stablecoins. Practus LLP: concluded that Kenzi Wang is the person who stole the stablecoins, and further discovered he also stole securities from investor Vivian Liu.

The board filed a lawsuit to recover the stolen assets, supported by irrefutable on-chain proof.`,
    exhibits: ['exhibit-11'],
    evidence_ids: ['ascent-audit', 'dhty-report', 'practus-report'],
    cross_references: [
      { section_id: 'section-12', reason: 'Investigation uncovered the $4.87M embezzlement', strength: 0.95 },
      { section_id: 'section-16', reason: 'Practus discovered Vivian Liu securities theft', strength: 0.85 },
      { section_id: 'section-6', reason: 'DHTY disproved Black Swan — confirms confrontation findings', strength: 0.90 },
    ],
    key_entities: ['Brad Bao', 'Francois Granada', 'Practus LLP', 'Ascent Fund Services', 'DHTY'],
    key_facts: [
      'Ascent: shadow ledger, $4.15M diverted from 79 investors',
      'DHTY: $4,432,400 confirmed diverted to personal wallets',
      'Practus: "Wang induced investors to provide funds to wallets controlled solely by Wang"',
      'Additional discovery: securities theft from Vivian Liu',
    ],
    gaps: [],
    last_regenerated: '2024-11-07',
    regeneration_log: [
      { date: '2023-12-01', trigger: 'ascent-audit', changes: 'Shadow ledger discovered, $4.15M quantified' },
      { date: '2024-02-28', trigger: 'dhty-report', changes: '$4,432,400 confirmed, Black Swan disproved' },
      { date: '2024-11-07', trigger: 'practus-report', changes: 'Legal conclusion: Kenzi stole stablecoins + Vivian securities' },
    ],
  },
  {
    id: 'section-12', number: 12, title: 'Embezzlement of Investor Funds ($4.87M)',
    content: `Kenzi, acting as the sole intermediary for Cere's fundraising, diverted $4.15 million from 79 investors in the Private and Influencer rounds to wallets he personally controlled. He used DocuSign to send SAFT emails from kenzi@cere.network directing investors to deposit funds to his personal wallets — each investor received a unique deposit address to obscure the trail.

Ascent certified that Seed and Strategic rounds were fully accounted for — the shortfall exists exclusively in the rounds Kenzi personally managed. DHTY independently confirmed $4,432,400 diverted. Kenzi maintained a shadow "Private Token Raise Tracker" spreadsheet to track his diversions, then revoked company access when discovered.`,
    exhibits: ['exhibit-12'],
    evidence_ids: ['ascent-audit', 'dhty-report', 'practus-report'],
    cross_references: [
      { section_id: 'section-11', reason: 'Discovered through board investigation', strength: 0.95 },
      { section_id: 'section-16', reason: 'Same fund diversion pattern used for Vivian Liu tokens', strength: 0.85 },
      { section_id: 'section-13', reason: 'Revoked Token Sale Tracker access = evidence destruction', strength: 0.80 },
    ],
    key_entities: ['Kenzi Wang', 'DocuSign', 'Republic', 'LD Capital'],
    key_facts: [
      'Private Round short $3,641,400',
      'Influencer Round short $378,000+',
      'Total: $4,423,400 (DHTY) / $4.87M+ including Influencer',
      'Seed/Strategic rounds 100% accounted for — only Kenzi-managed rounds short',
      'Unique wallet per investor to obscure diversion trail',
      'Shadow "Token Raise Tracker" maintained separately from company records',
    ],
    gaps: [],
    last_regenerated: '2024-02-28',
    regeneration_log: [],
  },
  {
    id: 'section-14', number: 14, title: 'Seizure of Corporate Digital Assets and Social Media Hijacking',
    content: `Kenzi systematically seized control of Cere's most valuable corporate assets. He stole the 105,000-follower @cerenetwork Twitter/X account and the 75,000-member Telegram group, locking out all employees including the founder, administrators, and CEO.

Beginning December 24, 2022, Kenzi changed the Twitter password three times. On April 18, 2023, he removed Fred Jin and Martijn Broersma as administrators from all Telegram channels. On September 22, 2023, he posted on the hijacked @cerenetwork claiming it was the "ONLY official account on X."

He then created fraudulent websites: cerenetwork.io, cerenetworkvictims.com, and coinyada.com. The consequential damages are quantified at over $198M.`,
    exhibits: ['exhibit-14'],
    evidence_ids: ['kenzi-files-pdf'],
    cross_references: [
      { section_id: 'section-13', reason: 'Digital asset seizure is evidence destruction at scale', strength: 0.75 },
      { section_id: 'section-8', reason: 'Hijacking was threatened during coercion campaign', strength: 0.70 },
    ],
    key_entities: ['Kenzi Wang', '@cerenetwork', 'Martijn Broersma', 'Fred Jin', 'cerenetwork.io', 'cerenetworkvictims.com'],
    key_facts: [
      '105K-follower Twitter hijacked, all admins locked out',
      '75K-member Telegram hijacked, Fred and Martijn removed',
      'Created fraudulent cerenetwork.io, cerenetworkvictims.com, coinyada.com',
      'cerenetworkvictims.com and coinyada.com share identical WHOIS/registration',
      'Damages quantified at $198M (Financial Substantiation Report)',
    ],
    gaps: [],
    last_regenerated: '2026-03-23',
    regeneration_log: [],
  },
  {
    id: 'section-15', number: 15, title: 'Ponzi-Style Money Laundering Through Symbolic Capital',
    content: `The proceeds of Kenzi's theft were systematically laundered. Stolen proceeds from multiple victims were routed to fund Symbolic Ventures ($50M unregistered fund) co-founded with Polygon's Sandeep Nailwal. Kenzi's $3M "Black Swan" theft partially funded the seed.

Kenzi married Sachi Kamiya, who serves as Director of Venture at Sentient Foundation and VP at Symbolic Capital. Kenzi, Nailwal, and Kamiya are now all principals at Sentient AI ($85M raised from Founders Fund, Pantera Capital). This creates a closed-loop self-dealing machine. Neither Symbolic Capital nor AU21 Capital is registered with SEC or FINRA.

This is textbook money laundering: stolen funds transformed into a legitimate-appearing venture vehicle.`,
    exhibits: ['exhibit-15'],
    evidence_ids: ['big-report', 'kenzi-files-pdf'],
    cross_references: [
      { section_id: 'section-17', reason: 'Symbolic Capital is the syndicate\'s financial infrastructure', strength: 0.90 },
      { section_id: 'section-4', reason: 'Pump-and-dump proceeds funded Symbolic', strength: 0.70 },
      { section_id: 'section-16', reason: 'Stolen tokens liquidated through Gate.io → Symbolic', strength: 0.75 },
    ],
    key_entities: ['Kenzi Wang', 'Sandeep Nailwal', 'Sachi Kamiya', 'Symbolic Ventures', 'Sentient AI', 'AU21 Capital'],
    key_facts: [
      '$50M unregistered fund, not SEC/FINRA registered',
      'Co-founded with Sandeep Nailwal (Polygon)',
      'Kenzi married Sachi Kamiya — dual role at Symbolic + Sentient',
      'Sentient AI: $85M from Founders Fund, Pantera',
      'Closed-loop: fund invests in project its founders control',
    ],
    gaps: ['Need to prove Nailwal knew about stolen source funds'],
    last_regenerated: '2026-02-01',
    regeneration_log: [],
  },
  {
    id: 'section-16', number: 16, title: 'Vivian Liu Token Theft (33.3M CERE)',
    content: `Kenzi stole 33.3 million CERE tokens from investor Vivian Liu. He volunteered to manage her account while she was pregnant and unavailable. A "Deleted User" replaced Vivian's wallet address in the distribution sheet.

Tokens were sent to the fake wallet in two tranches (13.33M on March 25, 2022 and 20M on May 10, 2022). After 19 months of dormancy, Kenzi used the bridge with 33,333 tokens (test transaction), then bridged the full 33.3M to Polygon, then Ethereum, and sold everything on KuCoin within 24 hours.

Three days later, the SAME bridge wallet (0xb08f...) received 30.6M RAZE tokens and 5.3M SKYRIM tokens. The February 2026 BIG forensic report proved Kenzi's personal wallet funded this bridge wallet. This is the smoking gun connecting Cere theft to RAZE and SKYRIM theft.

Kenzi then orchestrated Vivian Liu's $100M RICO lawsuit against Cere — weaponizing the very investor whose tokens he stole as plaintiff.`,
    exhibits: ['exhibit-16'],
    evidence_ids: ['big-report', 'kenzi-files-pdf'],
    cross_references: [
      { section_id: 'section-17', reason: 'Bridge wallet connects CERE/RAZE/SKYRIM — syndicate infrastructure', strength: 0.92 },
      { section_id: 'section-12', reason: 'Same wallet substitution pattern as investor fund diversion', strength: 0.85 },
      { section_id: 'section-15', reason: 'Liquidation through Gate.io (Chandler Guo) → Symbolic', strength: 0.75 },
      { section_id: 'section-3', reason: '"Deleted User" in edit history — alias/account manipulation', strength: 0.75 },
    ],
    key_entities: ['Kenzi Wang', 'Vivian Liu', 'Goopal Digital Limited', '0xb08f...', 'KuCoin', 'Gate.io', 'Dylan Dewdney'],
    key_facts: [
      'Volunteered to manage Vivian\'s account while pregnant',
      '"Deleted User" replaced wallet address in distribution sheet',
      'Two tranches: 13.33M (Mar 2022) + 20M (May 2022)',
      '19-month dormancy → test bridge → full dump in 24h',
      'Bridge wallet 0xb08f received 30.6M RAZE + 5.3M SKYRIM 3 days later',
      'BIG report: Kenzi\'s personal wallet funded the bridge wallet',
      'Dylan Dewdney can testify Kenzi controlled RAZE allocations via AU21',
    ],
    gaps: ['Need exact Slack screenshot of Kenzi taking over Vivian communication (Dec 23, 2021)'],
    last_regenerated: '2026-03-23',
    regeneration_log: [
      { date: '2026-02-13', trigger: 'big-report', changes: 'BIG connects bridge wallet to CERE, RAZE, SKYRIM — smoking gun' },
    ],
  },
  {
    id: 'section-17', number: 17, title: 'Digital Crime Syndicate Collaboration',
    content: `Kenzi does not operate alone. He relies on a distributed digital crime syndicate across San Francisco, Dubai, Beijing, and Singapore. He conspired with Vivian Liu (weaponized as plaintiff for RICO lawsuit), Kevin Xu/Yingkai Xu (BlockVC, dumped 50M tokens), Chandler Guo (Gate.io liquidation vehicle), and Sandeep Nailwal (Symbolic Capital co-founder).

"Josef Qu" is a fabricated KYC front managed by Kevin Ding. Each conspirator serves a specific function to exploit jurisdictional gaps, scale misrepresentations, and evade accountability.

This is not isolated opportunism — it is a serial, multi-million-dollar racketeering operation entirely reliant on repeated theft.`,
    exhibits: ['exhibit-18'],
    evidence_ids: ['kenzi-files-pdf', 'big-report', 'qri-report-3'],
    cross_references: [
      { section_id: 'section-16', reason: 'Bridge wallet connects all stolen tokens through syndicate', strength: 0.92 },
      { section_id: 'section-4', reason: 'LD Capital payout to syndicate member', strength: 0.90 },
      { section_id: 'section-15', reason: 'Symbolic Capital is syndicate financial vehicle', strength: 0.90 },
      { section_id: 'section-18', reason: 'Unlicensed broker-dealer enables syndicate operations', strength: 0.80 },
    ],
    key_entities: ['Kenzi Wang', 'Kevin Xu', 'Vivian Liu', 'Chandler Guo', 'Sandeep Nailwal', 'Josef Qu', 'Kevin Ding', 'Gate.io'],
    key_facts: [
      'Syndicate spans SF, Dubai, Beijing, Singapore',
      'Vivian Liu weaponized as $100M RICO plaintiff',
      'Kevin Xu dumped 50M tokens + attempted double-dip on Vivian\'s',
      'Gate.io (Chandler Guo) used for every liquidation',
      '"Josef Qu" = Kevin Ding\'s relative used as KYC front',
      'Nailwal co-founded Symbolic with stolen funds',
    ],
    gaps: ['Need testimony linking Kenzi directly to each conspirator\'s specific role in Goopal filing'],
    last_regenerated: '2026-02-13',
    regeneration_log: [
      { date: '2023-11-17', trigger: 'qri-report-3', changes: 'Multiple victim pattern identified' },
      { date: '2026-02-13', trigger: 'big-report', changes: 'Bridge wallet connects CERE/RAZE/SKYRIM across victims' },
    ],
  },
  {
    id: 'section-18', number: 18, title: 'Unlicensed Broker-Dealer Activity (SEC Violation)',
    content: `The entire criminal enterprise is built upon a foundational violation of federal securities law. Victims unanimously declare that Kenzi inserted himself into their projects by misrepresenting himself as a legitimate, licensed fundraiser and broker-dealer.

AU21 Capital and Beacon Accelerator explicitly advertise transaction-based compensation. Beacon describes investing $250K at $8M post-money, taking 3.125% equity plus 3.125% tokens. Yet neither Kenzi nor his funds are registered with SEC or FINRA.

In Cere's case, he facilitated the sale of Reg D registered securities ($26.3M from 2,526 investors on Republic) in direct violation of 15 USC 78o. Dylan Dewdney is prepared to testify under oath that Kenzi positioned himself as a licensed fundraiser.`,
    exhibits: ['exhibit-19'],
    evidence_ids: ['kenzi-files-pdf'],
    cross_references: [
      { section_id: 'section-1', reason: 'Fake credentials enabled the unlicensed activity', strength: 0.85 },
      { section_id: 'section-17', reason: 'Syndicate operations depend on appearing licensed', strength: 0.80 },
    ],
    key_entities: ['Kenzi Wang', 'AU21 Capital', 'Beacon Accelerator', 'Republic', 'Dylan Dewdney', 'SEC', 'FINRA'],
    key_facts: [
      'Facilitated $26.3M Reg D offering without registration',
      '2,526 investors on Republic',
      'Beacon: $250K at $8M, 3.125% equity + 3.125% tokens',
      'Neither AU21 nor Symbolic registered with SEC/FINRA',
      'Dylan Dewdney prepared to testify re: licensed fundraiser claim',
    ],
    gaps: ['Aggregate investor loss calculation needed'],
    last_regenerated: '2026-02-01',
    regeneration_log: [],
  },
];

// === EVIDENCE FILE KNOWLEDGE GRAPHS ===

export const EVIDENCE_GRAPHS: EvidenceGraph[] = [
  {
    id: 'dhty-report', title: 'DHTY Forensic Report', type: 'forensic_report', source: 'DHTY Financial Advisory Services', date: '2024-02-28',
    summary: 'Independent forensic audit confirming $4,432,400 in unaccounted investor funds diverted to Kenzi-controlled wallets. No on-chain evidence of Convex Finance "Black Swan" loss. Funds traced to personal Binance wallet.',
    key_findings: [
      '$14,426,850 total SAFT incoming across all rounds',
      '$10,003,450 in company wallets 1-4',
      '$4,423,400 UNACCOUNTED — diverted to Kenzi-controlled wallets',
      'Kenzi created unique wallet address per investor to obscure trail',
      'Over $4M raised from 75 investors — Kenzi did not account for nor communicate',
      'No on-chain evidence of Convex Finance activity — Black Swan story disproved',
      'Funds commingled with personal cryptocurrency in Kenzi\'s Binance wallet',
    ],
    entities: ['Kenzi Wang', 'Binance', 'Convex Finance', 'LedgerPrime'],
    connected_sections: ['section-6', 'section-11', 'section-12', 'section-10'],
    connected_evidence: [
      { id: 'ascent-audit', relationship: 'corroborates — Ascent found same $4.15M gap' },
      { id: 'practus-report', relationship: 'legal conclusion built on DHTY findings' },
    ],
    chain_of_custody: ['DHTY File 23-4032-01', 'Prepared for Independent Directors Brad Bao and Francois Granade'],
    last_regenerated: '2024-02-28',
  },
  {
    id: 'big-report', title: 'BIG Forensic Report — Vivian Liu Wallets', type: 'forensic_report', source: 'Blockchain Intelligence Group', date: '2026-02-13',
    summary: 'Court-ready blockchain forensics tracing stolen token movements. Bridge wallet 0xb08f... received stolen CERE (33.3M), then RAZE (30.6M) and SKYRIM (5.3M) three days later. Kenzi\'s confirmed personal wallet provided ETH gas to fund the bridge wallet. All tokens liquidated through Gate.io.',
    key_findings: [
      'Bridge wallet 0xb08f79488D335FBc7E0881c78ba341dA1f249f00 is the central node',
      'Received 33.3M stolen CERE tokens after Polygon→Ethereum bridge',
      'Three days later: received 30.6M RAZE + 5.3M SKYRIM from AU21 distributions',
      'Kenzi\'s personal wallet (0x0d07...92fe) funded the bridge wallet with ETH gas',
      'All tokens sold through Gate.io (co-founded by AU21 partner Chandler Guo)',
      'Proves single actor controlled both CERE theft wallet and AU21 distribution wallet',
    ],
    entities: ['Kenzi Wang', '0xb08f...', 'Gate.io', 'Chandler Guo', 'Vivian Liu', 'RAZE', 'SKYRIM', 'AU21 Capital'],
    connected_sections: ['section-16', 'section-17', 'section-15'],
    connected_evidence: [
      { id: 'dhty-report', relationship: 'DHTY traced fund diversions; BIG traced token movements' },
      { id: 'kenzi-files-pdf', relationship: 'Master document contextualizes BIG findings' },
    ],
    chain_of_custody: ['BIG Client Investigation for Martijn (Cere Network)', 'Court-admissible standard'],
    last_regenerated: '2026-02-13',
  },
  {
    id: 'practus-report', title: 'Practus LLP Internal Investigation Report', type: 'legal_report', source: 'Practus LLP', date: '2024-11-07',
    summary: 'Independent law firm investigation (March-July 2024). Conclusion: "Wang induced Company investors to provide funds to wallets controlled solely by Wang and Wang failed to report those contributions to the Company." Cleared Fred Jin of any wrongdoing. Discovered additional securities theft from Vivian Liu.',
    key_findings: [
      'No evidence supporting Wang\'s allegations against Fred Jin',
      'Wang directed investors to pay into his personal wallets via DocuSign from kenzi@cere.network',
      'Wang maintained shadow "Token Sale Tracker" — revoked company access prior to April 8, 2023',
      'Practus verified subset of DHTY/Ascent transactions against Etherscan',
      'Additional discovery: Kenzi stole securities by never delivering to Vivian Liu',
      'Formal conclusion: embezzlement of company AND investor assets',
    ],
    entities: ['Kenzi Wang', 'Fred Jin', 'Vivian Liu', 'Brad Bao', 'Francois Granade', 'Martijn Broersma'],
    connected_sections: ['section-11', 'section-12', 'section-16'],
    connected_evidence: [
      { id: 'dhty-report', relationship: 'Practus reviewed and verified DHTY forensic data' },
      { id: 'ascent-audit', relationship: 'Practus reviewed Ascent findings independently' },
    ],
    chain_of_custody: ['Practus LLP Memorandum to Board of Directors', 'Investigation March 15 - July 15, 2024', 'Report finalized November 7, 2024'],
    last_regenerated: '2024-11-07',
  },
  {
    id: 'ascent-audit', title: 'Ascent Fund Services Audit', type: 'forensic_report', source: 'Ascent Group (KFintech subsidiary)', date: '2023-12-01',
    summary: 'Comprehensive forensic accounting of all Cere funding rounds. Seed and Strategic rounds fully accounted for. Private Round short $3,641,400 and Influencer Round short $378,000+. Total $4.15M diverted from 79 investors. Kenzi-controlled wallets received $1,532,000 directly.',
    key_findings: [
      'Total raised across all rounds: $41,630,285',
      'Seed/Strategic: fully received and accounted for',
      'Private Round: short $3,641,400',
      'Influencer Round: short $378,000+',
      '$1,532,000 received directly in Kenzi-controlled wallets',
      '35+ investors with missing SAFT agreements',
      '40+ investors had funds sent to Kenzi-controlled wallets',
    ],
    entities: ['Kenzi Wang', 'Republic', 'DaoMaker', 'Polkastarter'],
    connected_sections: ['section-11', 'section-12'],
    connected_evidence: [
      { id: 'dhty-report', relationship: 'DHTY independently confirmed $4,432,400 — larger than Ascent estimate' },
      { id: 'practus-report', relationship: 'Practus relied on Ascent data for legal conclusions' },
    ],
    chain_of_custody: ['Ascent Group / KFintech letterhead', 'CERE Summary Report', 'November 15, 2023'],
    last_regenerated: '2023-12-01',
  },
  {
    id: 'qri-report-1', title: 'QRI Private Investigation Report', type: 'investigation', source: 'QRI', date: '2023-09-22',
    summary: 'First of three private investigation reports. Confirmed Grand Theft charge (Case 18017577). Vijay Garg $130K+ stolen — same wallet pattern. Employment history fabricated.',
    key_findings: [
      'Grand Theft charge confirmed: SFSC Case 18017577, 487(a)',
      'Vijay Garg: personal wallet directed instead of fund wallet',
      'Garg MO description: "Tell a big story, get you to sign, then shakes you down"',
      '"Stealing a car is not exactly part of the resume of a fund manager" — QRI investigator',
    ],
    entities: ['Kenzi Wang', 'Vijay Garg', 'HBUS'],
    connected_sections: ['section-2', 'section-1'],
    connected_evidence: [
      { id: 'qri-report-2', relationship: 'Continuation of investigation' },
      { id: 'qri-report-3', relationship: 'Final investigative findings' },
    ],
    chain_of_custody: ['QRI Report, Attorney Work Product, Steptoe & Johnson LLP'],
    last_regenerated: '2023-09-22',
  },
  {
    id: 'qri-report-3', title: 'QRI Third Report', type: 'investigation', source: 'QRI', date: '2023-11-17',
    summary: 'Third and final QRI report. Emmie Chang interview: confirmed fake Columbia/Wharton via National Student Clearinghouse. Y Combinator kicked out. Multiple victim testimonies. Vijay Garg MO description. Paralink competing project confirmed by Denko Mancheski.',
    key_findings: [
      'Emmie Chang: Wang "lied about having graduated from Columbia and Wharton"',
      'National Student Clearinghouse: "no record found"',
      'Alex Gold: Wang attended UNLV',
      'Y Combinator: kicked out for submitting under two companies',
      'Vijay Garg: fired from Huobi for "many bad reasons"',
      'Multiple victim pattern: Paralink, Domination Finance, Reef Finance',
    ],
    entities: ['Kenzi Wang', 'Emmie Chang', 'Alex Gold', 'Vijay Garg', 'Denko Mancheski'],
    connected_sections: ['section-1', 'section-17'],
    connected_evidence: [
      { id: 'qri-report-1', relationship: 'First report in series' },
    ],
    chain_of_custody: ['QRI Third Report, Attorney Work Product, Steptoe & Johnson LLP', 'November 17, 2023'],
    last_regenerated: '2023-11-17',
  },
];
